### PR TITLE
Disable all `github-comment-op` commands except `/reviewer`

### PR DESCRIPTION
**Pull request by timja**
see 
- https://github.com/jenkins-infra/helpdesk/issues/3074
- https://github.com/timja/github-comment-ops/releases/tag/v1.3.0

### CODE REVIEW

**Review by hervelemeur — APPROVED** [review]
I would have expected to add only the command to enable to the config but it's fine as it is already.

Thanks @timja!

**Comment by timja** [comment]
> I would have expected to add only the command to enable to the config but it's fine as it is already.
> 
> Thanks @timja!

they default to enabled currently, possibly should default to off so new commands don't get accidentally enabled, anyway this is explicit in what is there

**Comment by hervelemeur** [comment]
Default to `off` seems better, and complete explicit listing is totally appropriate here indeed.

**Comment by timja** [comment]
https://github.com/timja/github-comment-ops/issues/69

**Pull request merged**
