### PR TITLE
Add release drafter for infra

### PR DESCRIPTION
**Pull request by timja**
Mostly the same as jenkinsci, added a couple of new options with version resolution to try out

### CODE REVIEW

**Comment by timja** [comment]
no idea who has access here, @oleg-nenashev @daniel-beck ?

**Review by halkeye — APPROVED** [review]

**Comment by halkeye** [comment]
yea not me, but looks nice

**Comment by timja** [comment]
fyi @jetersen in case you have an opinion

**Review by olblak — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Sorry, I missed the comment. We could simplify it by inheriting bits from the jenkinsci Release Drafter settings.  Duplication is not a big deal, but still. Also, projects can inherit Release Drafter settings from other orgs, e.g. see https://github.com/jenkins-infra/plugin-site/blob/master/.github/release-drafter.yml

**Pull request merged**
